sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
    
language: scala

env:
  global:
    - OS=$(uname -s)

script: mvn clean compile test

scala:
   - 2.10.5

jdk:
  - oraclejdk8

