env:
  global:
    - OS=$(uname -s)
    - PATH=$HOME/.local/bin:$PATH
    - S3_BUCKET_CACHE=s3://rs-travis/kutuapp/build-cache

branches:
  only:
    - master
    - v2-networked
  
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

stages:
  - client
  - server

jobs:
  include:
  - stage: client
    language: node_js
    before_install:
      - npm install -g ionic
      - pip install --user awscli
      - ./ecr_credentials.sh
      - mkdir -p ~/$TRAVIS_BUILD_NUMBER
      - aws s3 sync $S3_BUCKET_CACHE/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
      - mkdir -p ~/requisites
      - aws s3 sync $S3_BUCKET_REQUISITES ~/requisites
    script:
      - cd $TRAVIS_BUILD_DIR/client/resultcatcher
      - npm install
      - ionic build --prod
      - cp -R -f ./www ~/$TRAVIS_BUILD_NUMBER/
      - rm -rf ~/requisites
    after_success:
      - aws s3 sync ~/$TRAVIS_BUILD_NUMBER $S3_BUCKET_CACHE/$TRAVIS_BUILD_NUMBER  
  - stage: server
    language: java
    os: osx
    osx_image: xcode9.2
    before_install:
      - pip install --user awscli
      - ./ecr_credentials.sh
      - mkdir -p ~/$TRAVIS_BUILD_NUMBER
      - aws s3 sync $S3_BUCKET_CACHE/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
    script:
      - cp -R -f ~/$TRAVIS_BUILD_NUMBER/www/* $TRAVIS_BUILD_DIR/src/main/resources/app
      - mvn clean package
      - cp -f $TRAVIS_BUILD_DIR/target/KuTu-app.jar $TRAVIS_BUILD_DIR/outputs/server/release
      - cp -f $TRAVIS_BUILD_DIR/$OS/bundles/*.msi $TRAVIS_BUILD_DIR/outputs/server/release/$OS
      - cp -f $TRAVIS_BUILD_DIR/$OS/bundles/*.dmg $TRAVIS_BUILD_DIR/outputs/server/release/$OS
      - cp -f $TRAVIS_BUILD_DIR/$OS/bundles/*.pkg $TRAVIS_BUILD_DIR/outputs/server/release/$OS
    after_success:
      - aws s3 rm --recursive $S3_BUCKET_CACHE/$TRAVIS_BUILD_NUMBER # clean up after ourselves
    

  
# script: mvn clean deploy --settings deploy-settings.xml
# script: mvn clean deploysite --settings deploy-settings.xml

deploy:
  # deploy build to s3
  provider: s3
  access_key_id: $aws_user
  secret_access_key: $aws_accesskey
  region: "eu-west-1"
  bucket: "rs-travis"
  local_dir: ./outputs
  upload_dir: public/kutuapp
  skip_cleanup: true    