env:
  global:
    - OS=$(uname -s)
    - PATH=$HOME/.local/bin:$PATH
    - S3_BUCKET_CACHE=s3://rs-travis/kutuapp/build-cache
    - S3_BUCKET_REQUISITES=s3://rs-travis/kutuapp/requisites

branches:
  except:
  - /^travisbuild-[0-9a-z\-]*/
      
# branches:
#   only:
#     - master
#     - v2-networked
  
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/outputs/$OS
  
stages:
  - client
  - server

jobs:
  include:
  - stage: client
    language: node_js
    addons:
      apt:
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
        - npm
        - jq
    before_install:
      - nvm install 8
      - npm install -g cordova ionic
      - pip install --user awscli
      - ./ecr_credentials.sh
      - mkdir -p ~/$TRAVIS_BUILD_NUMBER
      - aws s3 sync $S3_BUCKET_CACHE/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
      - mkdir -p ~/requisites
      - aws s3 sync $S3_BUCKET_REQUISITES ~/requisites
    script:
      - cd $TRAVIS_BUILD_DIR/client/resultcatcher
      - npm install
      - ionic build --prod
      - cp -R -f ./www ~/$TRAVIS_BUILD_NUMBER/
      - cp -R -f ~/$TRAVIS_BUILD_NUMBER/www/* $TRAVIS_BUILD_DIR/src/main/resources/app
      - rm -rf ~/requisites
    after_success:
      - git config --global user.email "builds@travis-ci.com"
      - git config --global user.name "Travis CI"
      - git add $TRAVIS_BUILD_DIR/src/main/resources/app
      - git commit -a -m "update with generated Client from TravisCI for build $TRAVIS_BUILD_NUMBER"
      - export GIT_TAG=travisbuild-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
      - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
      - git push -q https://$github_oauth2Token_KuTu@github.com/luechtdiode/KuTu $GIT_TAG > /dev/null 2>&1
      - aws s3 sync ~/$TRAVIS_BUILD_NUMBER $S3_BUCKET_CACHE/$TRAVIS_BUILD_NUMBER  
  - stage: server
    language: java
    os: osx
    osx_image: xcode9.2
    before_install:
      - brew install awscli
      - ./ecr_credentials.sh
      - mkdir -p ~/$TRAVIS_BUILD_NUMBER
      - aws s3 sync $S3_BUCKET_CACHE/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
    script:
      - cp -R -f ~/$TRAVIS_BUILD_NUMBER/www/* $TRAVIS_BUILD_DIR/src/main/resources/app
      - mvn clean deploy --settings deploy-settings.xml
      - cp -f $TRAVIS_BUILD_DIR/target/KuTu-app.jar $TRAVIS_BUILD_DIR/outputs/
      - cp -f $TRAVIS_BUILD_DIR/target/$OS/bundles/*.dmg $TRAVIS_BUILD_DIR/outputs/$OS/
      - cp -f $TRAVIS_BUILD_DIR/target/$OS/bundles/*.pkg $TRAVIS_BUILD_DIR/outputs/$OS/
    after_success:
      - aws s3 rm --recursive $S3_BUCKET_CACHE/$TRAVIS_BUILD_NUMBER # clean up after ourselves

deploy:
  # deploy build to s3
  - provider: s3
    access_key_id: $aws_user
    secret_access_key: $aws_accesskey
    region: "eu-west-1"
    bucket: "rs-travis"
    local_dir: $TRAVIS_BUILD_DIR/outputs
    upload_dir: kutuapp
    skip_cleanup: true
  
  # - provider: releases
  #   api_key: $github_oauth2Token_KuTu
  #   file_glob: true
  #   file: $TRAVIS_BUILD_DIR/src/main/resources/app
  #   skip_cleanup: true
  #   on:
  #     tags: true
  