# just working on linux ...
addons:
  apt:
    packages:
      - oracle-java8-installer

# just working on osx ...
# before_install:
#   - "wget --no-cookies --no-check-certificate --header \"Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u152-b16/aa0333dd3019491ca4f6ddbe78cdb6d0/jdk-8u152-macosx-x64.dmg" 
#   - hdiutil mount jdk-8u102-macosx-x64.dmg
#   - sudo installer -pkg /Volumes/JDK\ 8\ Update\ 102/JDK\ 8\ Update\ 102.pkg -target LocalSystem
#   - export JAVA_HOME=$(/usr/libexec/java_home)
  
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
    
language: java

env:
  global:
    - OS=$(uname -s)

jdk:
  - oraclejdk8

os:
#   - linux
  - osx
  
script: mvn site --settings deploy-settings.xml

branches:
  only:
    - master
