codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,files,footer
coverage:
  precision: 5
  range:
    - 18.0
    - 100.0
  round: up
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: true